## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("Weather_Database/WeatherPy_Database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Mataura,NZ,-46.1927,168.8643,50.49,35,6,2.44,clear sky
1,1,Takoradi,GH,4.8845,-1.7554,74.19,93,100,5.86,light rain
2,2,Thompson,CA,55.7435,-97.8558,59.16,63,40,0.00,scattered clouds
3,3,Busselton,AU,-33.6500,115.3333,59.04,80,48,13.80,scattered clouds
4,4,Kendari,ID,-3.9450,122.4989,82.96,68,100,2.37,overcast clouds

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
4,4,Kendari,ID,-3.9450,122.4989,82.96,68,100,2.37,overcast clouds
7,7,Faanui,PF,-16.4833,-151.7500,79.97,69,3,12.28,clear sky
18,18,Gizo,SB,-8.1030,156.8419,84.06,68,94,2.86,overcast clouds
19,19,Valvedditturai,LK,9.8167,80.1667,82.42,80,100,22.35,overcast clouds
21,21,Vaini,TO,-21.2000,-175.2000,77.16,73,75,6.91,broken clouds
23,23,Katsuura,JP,35.1333,140.3000,76.19,64,28,19.73,scattered clouds
26,26,Kapaa,US,22.0752,-159.3190,84.52,74,40,5.99,light rain
30,30,Hambantota,LK,6.1241,81.1185,77.34,94,20,8.05,few clouds
36,36,Balabac,PH,7.9868,117.0645,84.34,72,32,6.22,scattered clouds
37,37,Teknaf,BD,20.8624,92.3058,79.18,90,100,6.71,overcast clouds

In [5]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City_ID                239
City                   239
Country                239
Lat                    239
Lng                    239
Max Temp               239
Humidity               239
Cloudiness             239
Wind Speed             239
Current Description    239
dtype: int64

In [6]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
4,Kendari,ID,82.96,overcast clouds,-3.9450,122.4989,
7,Faanui,PF,79.97,clear sky,-16.4833,-151.7500,
18,Gizo,SB,84.06,overcast clouds,-8.1030,156.8419,
19,Valvedditturai,LK,82.42,overcast clouds,9.8167,80.1667,
21,Vaini,TO,77.16,broken clouds,-21.2000,-175.2000,
23,Katsuura,JP,76.19,scattered clouds,35.1333,140.3000,
26,Kapaa,US,84.52,light rain,22.0752,-159.3190,
30,Hambantota,LK,77.34,few clouds,6.1241,81.1185,
36,Balabac,PH,84.34,scattered clouds,7.9868,117.0645,
37,Teknaf,BD,79.18,overcast clouds,20.8624,92.3058,


hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

hotel_df["Hotel Name"] = ""
hotel_df.head(10)

In [7]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"

    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    # 7. Drop the rows where there is no Hotel Name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [11]:
#show modified hotel data frame
hotel_df.head(10)
# 8a. Create the output File (CSV)
output_data_file = "Vacation_Search/WeatherPy_vacation.csv.csv"
# 8b. Export the City_Data into a csv
hotel_df.to_csv(output_data_file, index_label="City_ID")

In [17]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = hotel_df[["Lat", "Lng"]]

In [18]:
# 11a. Add a marker layer for each city to the map. 
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))